#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE ckan;
    CREATE DATABASE datastore;
    GRANT ALL PRIVILEGES ON DATABASE ckan TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE datastore TO $POSTGRES_USER;
EOSQL
